//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagination.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersMaster
    {
        public long ID { get; set; }
        public Nullable<System.Guid> OrderCode { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public string OrderDescription { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string PriceMethod { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> StationID { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public string DiscountType { get; set; }
        public Nullable<double> AdditionalCharges { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string DeletionRemarks { get; set; }
        public Nullable<int> CreatedBySalesmanID { get; set; }
        public Nullable<int> PrioritySuggestion { get; set; }
        public string ItemTax { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ProductNature { get; set; }
    }
}
